// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import LogoSvg from "./logo.svg";

import './App.css';
import MyThread from "./mythread.worker.js";
;

var startWebWorker = (() => new MyThread());

function run(param) {
  var worker = Curry._1(startWebWorker, undefined);
  worker.onmessage = (function (e) {
      console.log("Worker\xe3\x81\x8b\xe3\x82\x89\xe5\x8f\x97\xe3\x81\x91\xe5\x8f\x96\xe3\x81\xa3\xe3\x81\x9f\xe3\x82\x82\xe3\x81\xae:" + e.data);
      
    });
  worker.postMessage("Hello, Worker!!!");
  
}

var logo = LogoSvg;

function hello(param) {
  console.log("hello, world!!");
  
}

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("textarea", undefined), React.createElement("header", {
                  className: "App-header"
                }, React.createElement("img", {
                      className: "App-logo",
                      alt: "logo",
                      src: logo
                    }), React.createElement("p", undefined, "Edit ", React.createElement("code", undefined, "src/App.js"), " and save to reload."), React.createElement("a", {
                      className: "App-link",
                      rel: "noopener noreferrer",
                      target: "_blank",
                      onClick: run
                    }, "Learn React")));
}

var make = App;

var $$default = App;

export {
  startWebWorker ,
  run ,
  logo ,
  hello ,
  make ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
