// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mpst$RescriptMpst from "rescript-mpst/src/Mpst.js";
import * as MpstWorker$RescriptMpst from "rescript-mpst/src/MpstWorker.js";
import * as Protocol$RescriptReactIntro from "./Protocol.js";

const marked = require("marked");
;

console.log("start");

MpstWorker$RescriptMpst.WorkerSide.init(Protocol$RescriptReactIntro.g, Protocol$RescriptReactIntro.webwork).then(function (ch) {
      return Mpst$RescriptMpst.receive(ch, (function (x) {
                      return {
                              NAME: "Main",
                              VAL: x
                            };
                    })).then(function (param) {
                  var match = param.VAL;
                  var m = marked(match[0]);
                  return Mpst$RescriptMpst.close(Mpst$RescriptMpst.send(match[1], (function (x) {
                                    return {
                                            NAME: "Main",
                                            VAL: x
                                          };
                                  }), (function (x) {
                                    return {
                                            NAME: "goodbye",
                                            VAL: x
                                          };
                                  }), m));
                });
    });

export {
  
}
/*  Not a pure module */
