// Generated by ReScript, PLEASE EDIT WITH CARE


const marked = require("marked");
;

function setOnMessage(f) {
  return (f => {
  onmessage = f;
})(f);
}

setOnMessage(function (e) {
      console.log("I got:" + e.data);
      var m = marked(e.data);
      console.log(m);
      postMessage(m);
      
    });

export {
  setOnMessage ,
  
}
/*  Not a pure module */
